variable "availability_zone" { type = string }
variable "flavor" { type = string }
variable "image_name" { type = string }
variable "manifest_path" { type = string }
variable "network" { type = string }
variable "provision_script" { type = string }
variable "security_group" { type = string }
variable "source_image" { type = string }
variable "ssh_key_path" { type = string }
variable "ssh_keypair_name" { type = string }
variable "ssh_username" { type = string }
variable "like" { type = string }
variable "major" { type = string }

source "openstack" "autogenerated_1" {
  availability_zone    = "${var.availability_zone}"
  flavor               = "${var.flavor}"
  image_name           = "${var.image_name}"
  networks             = "${var.network}"
  security_groups      = "${var.security_group}"
  source_image         = "${var.source_image}"
  ssh_keypair_name     = "${var.ssh_keypair_name}"
  ssh_private_key_file = "${var.ssh_key_path}"
  ssh_pty              = "true"
  ssh_username         = "${var.ssh_username}"
}

build {
  sources = ["source.openstack.autogenerated_1"]

  provisioner "shell" {
    scripts = [
      "scripts/uio-rhel.sh",
      "scripts/fstrim.sh",
      "scripts/qemu_guest_agent.sh",
      "scripts/upgrade.sh",
      "scripts/enable_ipv6.sh",
      "scripts/autopatch.sh",
      "scripts/report.sh",
      "scripts/sshd_hardening.sh",
      "${var.provision_script}",
      "scripts/cleanup.sh",
      "scripts/uio-cleanup.sh"]
  }

  post-processor "manifest" {
    output = "${var.manifest_path}"
  }
}
