variable "availability_zone" {
  type = string
  default = null
}
variable "flavor" { type = string }
variable "image_name" { type = string }
variable "manifest_path" {
  type = string
  default = null
}
variable "network" {
  type = string
  default = null
}
variable "provision_script" {
  type = string
  default = null
}
variable "security_group" {
  type = string
  default = null
}
variable "source_image" {
  type = string
  default = null
}
variable "ssh_key_path" {
  type = string
  default = null
}
variable "ssh_keypair_name" {
  type = string
  default = null
}
variable "ssh_username" {
  type = string
  default = null
}

locals {
  ipv6_script = [ "scripts/enable_ipv6.sh" ]
  provision_script = var.provision_script != null ? ["${var.provision_script}"] : []
}

local "scripts" {
  expression = concat(local.ipv6_script,
    [
      "scripts/uio-rhel.sh",
      "scripts/fstrim.sh",
      "scripts/qemu_guest_agent.sh",
      "scripts/upgrade.sh",
      "scripts/autopatch.sh",
      "scripts/report.sh",
      "scripts/sshd_hardening.sh",
    ],
      local.provision_script,
    [
      "scripts/cleanup.sh",
      "scripts/uio-cleanup.sh"
    ]
  )
}

source "openstack" "autogenerated_1" {
  availability_zone    = "${var.availability_zone}"
  flavor               = "${var.flavor}"
  image_name           = "${var.image_name}"
  networks             = var.network != null ? ["${var.network}"] : []
  security_groups      = var.security_group != null ? ["${var.security_group}"] : []
  source_image         = "${var.source_image}"
  ssh_keypair_name     = "${var.ssh_keypair_name}"
  ssh_private_key_file = "${var.ssh_key_path}"
  ssh_pty              = "true"
  ssh_username         = "${var.ssh_username}"
}

build {
  sources = ["source.openstack.autogenerated_1"]

  provisioner "shell" {
    scripts = local.scripts
  }

  post-processor "manifest" {
    output = "${var.manifest_path}"
  }
}
